### ISSUE TITLE
Please add a license file and a screen shot. And consider renaming the repo to `ys-zsh-theme`

### ISSUE THREAD

**Issue by unixorn** [sunrisewestern/my_zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the repository name is awfully generic. Please consider renaming it to `ys-zsh-theme` to match the theme file. I also prefer to add themes with screen shots in their readme so that users can see what they look like without having to install them.

Finally, please add a license file, some people won't use any code that doesn't have a license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by unixorn** [comment]
I don't see the license file or screen shot

**Comment by sunrisewestern** [comment]
Sorry, this repository is only a fork of another zsh theme (ohmyzsh/themes/ys.zsh-theme) with minor modification and is only for backup purpose.

**Comment by unixorn** [comment]
np, thanks
